void main() {
    int intOperandA = 8;
    int intOperandB = 4;
    int intSum;
    int intProduct;
    int intDifference;
    int intQuotient;
    int intModulo;
    double doubleOperandA = 3.50;
    double doubleOperandB = 1.75;
    double doubleSum;
    double doubleProduct;
    double doubleDifference;
    double doubleQuotient;
    intSum = intOperandA + intOperandB;
    System.out.println("The sum using ints of " + intOperandA + " and " + intOperandB + " is " + intSum);
    intProduct = intOperandA * intOperandB;
    System.out.println("The product using ints of " + intOperandA + " and " + intOperandB + " is " + intProduct);
    intDifference = intOperandA - intOperandB;
    System.out.println("The difference using ints of " + intOperandA + " and " + intOperandB + " is " + intDifference);
    intQuotient = intOperandA / intOperandB;
    System.out.println("The quotient using ints of " + intOperandA + " and " + intOperandB + " is " + intQuotient);
    intModulo = intOperandA % intOperandB;
    System.out.println("The modulo using ints of " + intOperandA + " and " + intOperandB + " is " + intModulo);
    doubleSum = doubleOperandA + doubleOperandB;
    System.out.println("The sum using ints of " + doubleOperandA + " and " + doubleOperandB + " is " + doubleSum);
    doubleProduct = doubleOperandA * doubleOperandB;
    System.out.println("The product using ints of " + doubleOperandA + " and " + doubleOperandB + " is " + doubleProduct);
    doubleDifference = doubleOperandA - doubleOperandB;
    System.out.println("The difference using ints of " + doubleOperandA + " and " + doubleOperandB + " is " + doubleDifference);
    doubleQuotient = doubleOperandA / doubleOperandB;
    System.out.println("The quotient using ints of " + doubleOperandA + " and " + doubleOperandB + " is " + doubleQuotient);

    double myLunchCost = 12.50;
    int numKidsInFamily = 3;
    boolean isRaining = false;
    double gasPrice = 3.99;
    int favNum = 17;
    double shoeSize = 8;
    int birthMonth = 1;
    String fullName = "Arpan Gill";
}
